version: '3.8'

services:
  api:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
    # -------- replace with comment to run with gunicorn --------
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/code

  postgres:
    image: postgis/postgis:16-3.5-alpine
    environment:
      POSTGRES_PASSWORD: "postgresanyjob"
      POSTGRES_USER: postgres
      POSTGRES_DB: anyjob
    volumes:
       - postgres-data-1:/var/lib/postgresql/data
    expose:
        - "5432"
    ports:
        - "5432:5432"
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    expose:
      - "6379"
    ports:
        - "6379:6379"      

volumes:
  postgres-data-1:
  redis-data:
