name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - DEV
          - TEST
          - STAGING
          - FEATURE
      testSuite:
        description: 'Test suite folder to run (e.g. sanity, sukima, payment, attendanceDetails)'
        required: true
        type: choice
        options:
          - Sanity
          - Sanity/Sukima
          - Sanity/PaymentSetting
          - Sanity/AttendanceDetails
  schedule:
    - cron: '5 4 * * *'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: |
          echo ${{ github.event.inputs.environment || 'STAGING' }}
          echo ${{ github.event.inputs.testSuite || 'Sanity/Sukima' }}
