name: Google Chat Notify
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Notify build start
        uses: hoangbvh/actions-google-chat-notification@v1.0.0
        with:
          name: "[DEV] Build GC-Admin-Service:"
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: in-progress
          # custom_text: 'Test start message.'
          
      - name: google-chat-notification
        uses: hoangbvh/actions-google-chat-notification@v1.0.0
        with:
          name: Build DEV 
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: failure
          custom_text: 'Test fail message.'
          
      - name: google-chat-notification
        uses: hoangbvh/actions-google-chat-notification@v1.0.0
        with:
          name: Build DEV
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}
          custom_text: 'Test success message.'
