name: Update AWS Lambda Functions

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target deployment environment'
        required: true
        type: choice
        options:
          - testing
          - staging
          - production
      functions:
        description: 'Target deployment function'
        required: true
        type: choice
        options:
          - update-function
          - create-function
          - select-function

permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    name: Update Lambda Function
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE }}
        aws-region: ${{ vars.AWS_REGION }}
        
