on:
  push:
    branches:
      - master
  workflow_dispatch:
      
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Notify Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,commit,author,ref,workflow,job,pullRequest
        mention: '<@U07F22U8YAF>'
        username: AutoTest
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
      if: always()          
    
    - name: Custom Slack Notification
      if: success()
      uses: slackapi/slack-github-action@v2.0.0
      with:
        webhook: ${{ secrets.SLACK_WEBHOOK }}
        webhook-type: webhook-trigger
        payload: |
          {
            "attachments": [
              {
                "color": "#36a64f",
                "pretext": "Build DEVELOP Success. Please verify! :rocket:",
                "fields": [
                  {
                    "title": "Ref",
                    "value": "${{ github.ref }}",
                    "short": true
                  },
                  {
                    "title": "Event",
                    "value": "${{ github.event_name }}",
                    "short": true
                  },
                  {
                    "title": "Actions URL",
                    "value": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Deploy DEV anyjob-frontend>"
                  },
                  {
                    "title": "Commit",
                    "value": "${{ github.sha }}",
                    "short": true
                  },
                  {
                    "title": "Message",
                    "value": "@NgocDNTT \n @LinhNTM \n @TienNQ"
                  }
                ]
              }
            ]
          }
