on: 
  push:
    branches:
      - master
      
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Notify Slack - Deployment Starting
      if: success()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_API_WEBHOOK_TOKEN }}
      uses: Discontract/github-action-slack-notify-deployment@v1
      with:
        channel_id: ${{ secrets.SLACK_API_CHANNEL_ID }}
        status: "${{ vars.SLACK_MENTION_USERS }} Build starting"
        color: "warning"
          
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: 'success'
        SLACK_MESSAGE: '${{ vars.SLACK_MENTION_USERS }} Post Content :rocket:'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: 'warning'
        SLACK_MESSAGE: '${{ vars.SLACK_MENTION_USERS }} Post Content :rocket:'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: 'failure'
        SLACK_MESSAGE: '${{ vars.SLACK_MENTION_USERS }} Post Content :rocket:'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }} 
        
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE: '${{ vars.SLACK_MENTION_USERS }} Post Content :rocket:'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}        
