on:
  push:
    branches:
      - master
  workflow_dispatch:
      
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # - name: Notify Slack - Deployment Starting
    #   if: success()
    #   env:
    #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_API_WEBHOOK_TOKEN }}
    #   uses: Discontract/github-action-slack-notify-deployment@v1
    #   with:
    #     channel_id: ${{ secrets.SLACK_API_CHANNEL_ID }}
    #     status: "${{ vars.SLACK_MENTION_USERS }} Build starting"
    #     color: "warning"
    
    # - name: Notify Slack
    #   uses: 8398a7/action-slack@v3
    #   with:
    #     status: ${{ job.status }}
    #     fields: repo,commit,author,ref,workflow,job,pullRequest
    #   env:
    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
    #   if: always()          

    - name: slack - GitHub Actions Slack integration
      # You may pin to the exact commit or the version.
      # uses: act10ns/slack@44541246747a30eb3102d87f7a4cc5471b0ffb7d
      uses: act10ns/slack@v2.1.0
      with:
        # Specify Slack Incoming Webhook URL
        webhook-url: ${{ secrets.SLACK_WEBHOOK }}
        # Configuration file
        # config: # optional, default is .github/slack.yml
        # # Specify success, failure, cancelled or a custom status
        # status: 
        # # Report on the status of individual steps
        # steps: # optional
        # # matrix properties
        # matrix: # optional
        # # Override default channel with different channel or username
        # channel: # optional
        # # Override message format for step
        # message: # optional
              
                
    # - name: Slack Notification
    #   uses: rtCamp/action-slack-notify@v2
    #   env:
    #     SLACK_COLOR: 'success'
    #     SLACK_MESSAGE: '${{ vars.SLACK_MENTION_USERS }} On success :rocket:'
    #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    # - name: Slack Notification
    #   uses: rtCamp/action-slack-notify@v2
    #   env:
    #     SLACK_COLOR: 'warning'
    #     SLACK_MESSAGE: '${{ vars.SLACK_MENTION_USERS }} Warning :rocket:'
    #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        
    # - name: Slack Notification
    #   uses: rtCamp/action-slack-notify@v2
    #   env:
    #     SLACK_COLOR: 'failure'
    #     SLACK_MESSAGE: '${{ vars.SLACK_MENTION_USERS }} On failure :rocket:'
    #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }} 
      
