name: Slack Notification Demo

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target Environment'
        required: true
        type: choice
        options:
          - develop
          - testing
          - staging
          - production

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - name: Notify slack starting
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: 'warning'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'Build ${{ github.event.inputs.environment }} Starting'
    # - uses: actions/checkout@v4

    # - name: Slack Post
    #   # You may pin to the exact commit or the version.
    #   # uses: devtk0582/slack-post-action@b9e9a7b9cb8f4cff41f6eacaf7b077f204e8a081
    #   uses: devtk0582/slack-post-action@v1.2
    #   with:
    #     # Slack Webhook Url
    #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    #     # Message to send
    #     MESSAGE: 'this message'
              
    # - name: Notify Slack
    #   uses: 8398a7/action-slack@v3
    #   with:
    #     status: ${{ job.status }}
    #     fields: repo,commit,author,ref,workflow,job,pullRequest
    #     mention: '<@U07F22U8YAF>'
    #     username: AutoTest
    #   env:
    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
    #   if: always()          
    
    # - name: Custom Slack Notification
    #   if: success()
    #   uses: slackapi/slack-github-action@v2.0.0
    #   with:
    #     webhook: ${{ secrets.SLACK_WEBHOOK }}
    #     webhook-type: webhook-trigger
    #     payload: ${{ vars.SLACK_PAYLOAD }}
          # {
          #   "attachments": [
          #     {
          #       "color": "#36a64f",
          #       "pretext": "Build DEVELOP Success. Please verify! :rocket:",
          #       "fields": [
          #         {
          #           "title": "Ref",
          #           "value": "${{ github.ref }}",
          #           "short": true
          #         },
          #         {
          #           "title": "Event",
          #           "value": "${{ github.event_name }}",
          #           "short": true
          #         },
          #         {
          #           "title": "Actions URL",
          #           "value": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Deploy DEV anyjob-frontend>"
          #         },
          #         {
          #           "title": "Commit",
          #           "value": "${{ github.sha }}",
          #           "short": true
          #         },
          #         {
          #           "title": "Message",
          #           "value": "@NgocDNTT \n @LinhNTM \n @TienNQ"
          #         }
          #       ]
          #     }
          #   ]
          # }
